name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Get commit hash
        id: sha
        run: echo "::set-output name=sha::${GITHUB_SHA::7}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build images and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: 'back.dockerfile'
          tags: |
            ghcr.io/thibaultnocchi/mon_petit_bac:back
            ghcr.io/thibaultnocchi/mon_petit_bac:back.${{ steps.sha.outputs.sha }}

      - name: Build images and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: 'front.dockerfile'
          tags: |
            ghcr.io/thibaultnocchi/mon_petit_bac:front
            ghcr.io/thibaultnocchi/mon_petit_bac:front.${{ steps.sha.outputs.sha }}
